[2024-02-07T15:24:30.879+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-postgres-dag.query_and_return_value manual__2024-02-07T15:15:49.542144+00:00 [queued]>
[2024-02-07T15:24:30.897+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-postgres-dag.query_and_return_value manual__2024-02-07T15:15:49.542144+00:00 [queued]>
[2024-02-07T15:24:30.898+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-02-07T15:24:30.929+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): query_and_return_value> on 2024-02-07 15:15:49.542144+00:00
[2024-02-07T15:24:30.938+0000] {standard_task_runner.py:60} INFO - Started process 6944 to run task
[2024-02-07T15:24:30.956+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-postgres-dag', 'query_and_return_value', 'manual__2024-02-07T15:15:49.542144+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/election_dag.py', '--cfg-path', '/tmp/tmp2de83fr8']
[2024-02-07T15:24:30.960+0000] {standard_task_runner.py:88} INFO - Job 270: Subtask query_and_return_value
[2024-02-07T15:24:31.038+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-postgres-dag.query_and_return_value manual__2024-02-07T15:15:49.542144+00:00 [running]> on host 4775ae97916b
[2024-02-07T15:24:31.136+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='El_mboup' AIRFLOW_CTX_DAG_ID='***-postgres-dag' AIRFLOW_CTX_TASK_ID='query_and_return_value' AIRFLOW_CTX_EXECUTION_DATE='2024-02-07T15:15:49.542144+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-07T15:15:49.542144+00:00'
[2024-02-07T15:24:31.147+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/election_dag.py", line 96, in query_table_and_store_value
    engine.execute(text("""
NameError: name 'text' is not defined
[2024-02-07T15:24:31.157+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=***-postgres-dag, task_id=query_and_return_value, execution_date=20240207T151549, start_date=20240207T152430, end_date=20240207T152431
[2024-02-07T15:24:31.174+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 270 for task query_and_return_value (name 'text' is not defined; 6944)
[2024-02-07T15:24:31.208+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-07T15:24:31.236+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
