[2024-02-06T22:16:26.729+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-postgres-dag.delete_table manual__2024-02-06T21:31:41.150201+00:00 [queued]>
[2024-02-06T22:16:26.747+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-postgres-dag.delete_table manual__2024-02-06T21:31:41.150201+00:00 [queued]>
[2024-02-06T22:16:26.747+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-06T22:16:26.769+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): delete_table> on 2024-02-06 21:31:41.150201+00:00
[2024-02-06T22:16:26.775+0000] {standard_task_runner.py:60} INFO - Started process 210 to run task
[2024-02-06T22:16:26.783+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '***-postgres-dag', 'delete_table', 'manual__2024-02-06T21:31:41.150201+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/election_dag.py', '--cfg-path', '/tmp/tmpug6h8g05']
[2024-02-06T22:16:26.792+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask delete_table
[2024-02-06T22:16:26.864+0000] {task_command.py:423} INFO - Running <TaskInstance: airflow-postgres-dag.delete_table manual__2024-02-06T21:31:41.150201+00:00 [running]> on host 4775ae97916b
[2024-02-06T22:16:26.963+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='El_mboup' AIRFLOW_CTX_DAG_ID='***-postgres-dag' AIRFLOW_CTX_TASK_ID='delete_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T21:31:41.150201+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T21:31:41.150201+00:00'
[2024-02-06T22:16:26.968+0000] {sql.py:276} INFO - Executing: DROP TABLE IF EXISTS candidatures_presidentielle ;
[2024-02-06T22:16:27.006+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/election_dag.py", line 217, in delete_table
    PostgresOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2024-02-06T22:16:27.012+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=***-postgres-dag, task_id=delete_table, execution_date=20240206T213141, start_date=20240206T221626, end_date=20240206T221627
[2024-02-06T22:16:27.027+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task delete_table (The conn_id `postgres_default` isn't defined; 210)
[2024-02-06T22:16:27.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T22:16:27.067+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
